let demos = {
    "Jingle Bells": `
(play
 (with-bpm 240
   (chord (note-seq (map (fn (add-adsr n) (with-adsr 1.2 0.05 0.075 1 0.9 n))
                    (chord (note (pitch-at C 2) 4)
                           (note (pitch-at G 2) 4))
                    (chord (note (pitch-at C 2) 4)
                           (note (pitch-at G 2) 4))
                    (chord (note (pitch-at C 2) 4)
                           (note (pitch-at G 2) 4))
                    (chord (note (pitch-at C 2) 4)
                           (note (pitch-at G 2) 4))
                    (chord (note (pitch-at F 2) 4)
                           (note (pitch-at A 3) 4))
                    (chord (note (pitch-at C 2) 4)
                           (note (pitch-at G 2) 4))
                    (chord (note (pitch-at F 2) 4)
                           (note (pitch-at G 2) 4))
                    (chord (note (pitch-at F 2) 4)
                           (note (pitch-at G 2) 4))))
          (note-seq (map (fn (add-adsr n) (with-adsr 1.2 0.2 0.3 1 0.9 n))
                    (note (pitch-at E 3) 1)
                    (note (pitch-at E 3) 1)
                    (note (pitch-at E 3) 2)
                    (note (pitch-at E 3) 1)
                    (note (pitch-at E 3) 1)
                    (note (pitch-at E 3) 2)
                    (note (pitch-at E 3) 1)
                    (note (pitch-at G 3) 1)
                    (note (pitch-at C 3) 1)
                    (note (pitch-at D 3) 1)
                    (note (pitch-at E 3) 4)
                    (note (pitch-at F 3) 1)
                    (note (pitch-at F 3) 1)
                    (note (pitch-at F 3) 1)
                    (note (pitch-at F 3) 1)
                    (note (pitch-at F 3) 1)
                    (note (pitch-at E 3) 1)
                    (note (pitch-at E 3) 1)
                    (note (pitch-at E 3) 1)
                    (note (pitch-at E 3) 1)
                    (note (pitch-at D 3) 1)
                    (note (pitch-at D 3) 1)
                    (note (pitch-at E 3) 1)
                    (note-seq (note (pitch-at D 3) 2)
                              (note (pitch-at G 3) 2)))))))
`,
    "Happy Birthday": `
(play (with-bpm 180 (with-known-timbre piano
  (note (pitch-at G 2) 0.5)
  (note (pitch-at G 2) 0.5)
  (note (pitch-at A 3) 1)
  (note (pitch-at G 2) 1)
  (note (pitch-at C 3) 1)
  (note (pitch-at B 3) 2)
  (note (pitch-at G 2) 0.5)
  (note (pitch-at G 2) 0.5)
  (note (pitch-at A 3) 1)
  (note (pitch-at G 2) 1)
  (note (pitch-at D 3) 1)
  (note (pitch-at C 3) 2)
  (note (pitch-at G 2) 0.5)
  (note (pitch-at G 2) 0.5)
  (note (pitch-at G 3) 1)
  (note (pitch-at E 3) 1)
  (note (pitch-at C 3) 0.5)
  (note (pitch-at C 3) 0.5)
  (note (pitch-at B 3) 1)
  (note (pitch-at A 3) 1)
  (note (pitch-at F 3) 0.5)
  (note (pitch-at F 3) 0.5)
  (note (pitch-at E 3) 1)
  (note (pitch-at C 3) 1)
  (note (pitch-at D 3) 1)
  (note (pitch-at C 3) 2))))
`,
    "Vibrato Glissando": `
(play (vibrato 5 10
  (glissando (pitch-at A 5)
             (pitch-at A 4) 5)))
`
}
